# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coupon',
            field=models.IntegerField(default=0, verbose_name='\u70b9\u5238'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u4e2a\u6027\u7b7e\u540d'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='\u90ae\u7bb1\u9a8c\u8bc1'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/%Y-%m-%d/', verbose_name='\u4e2a\u4eba\u7167\u7247'),
        ),
    ]
